name: Manual workflow
on:
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        usernm: ['Ramya','Saaya']
        timegreeting: ['Morning', ' Evening']
    steps:
    - name: Send greeting
      run: echo "Hello ${{ matrix.usernm}}. Good ${{ matrix.timegreeting}} !!"
  goodbye:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - name: Say GoodBye
        run: |
          echo "Goodbye"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=MyWarning::Missing semicolon"
          echo "::notice file=app.js,line=1,col=5,endColumn=7,title=MyNotice::Missing semicolon"
          echo "::warning :: This is a warning message"
          echo "::notice:: This is a debug message"
          echo "### Flying off! :rocket:" >> $GITHUB_STEP_SUMMARY
