name: Manual workflow
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        usernm: ['Ramya','Saaya','Vijay']
    steps:
    - name: Send greeting
      run: echo "Hello ${{ matrix.usernm}}"
