name: Manual workflow
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        usernm: ['Ramya','Saaya','Vijay']
        timegreeting: ['Morning', ' Evening']
    steps:
    - name: Send greeting
      run: echo "Hello ${{ matrix.usernm}}. Good ${{ matrix.timegreeting}} !!"
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say GoodBye
      - run: echo "Goodbye"
